#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { isJsonObject, type JsonValue } from "../src/core/json.js";
import { NUMBER_VALUE, STRING_VALUE } from "../src/core/value-schemas.js";
import { Check } from "typebox/value";

const BASE_URL = "https://openrouter.ai/api/v1";
const OUTPUT = resolve(dirname(fileURLToPath(import.meta.url)), "../src/images/models.generated.ts");
const MAX_CATALOG_BYTES = 8 * 1024 * 1024;

interface GeneratedModel {
  id: string;
  name: string;
  input: Array<"text" | "image">;
  output: Array<"text" | "image">;
  pricing?: { input: number; output: number; cacheRead: number; cacheWrite: number };
}

function modalities(value: JsonValue | undefined): Array<"text" | "image"> {
  if (!Array.isArray(value)) return [];
  return [...new Set(value.filter((entry): entry is "text" | "image" => entry === "text" || entry === "image"))];
}

function price(value: JsonValue | undefined): number | undefined {
  if (!Check(STRING_VALUE, value) && !Check(NUMBER_VALUE, value)) return 0;
  const parsed = Number(value) * 1_000_000;
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : undefined;
}

function parseModel(value: JsonValue): GeneratedModel | undefined {
  if (!isJsonObject(value)) return undefined;
  const architecture = isJsonObject(value.architecture) ? value.architecture : undefined;
  const sourcePricing = isJsonObject(value.pricing) ? value.pricing : undefined;
  if (
    !Check(STRING_VALUE, value.id) ||
    !Check(STRING_VALUE, value.name) ||
    value.id === "" ||
    Buffer.byteLength(value.id, "utf8") > 512 ||
    Buffer.byteLength(value.name, "utf8") > 2_048
  ) return undefined;
  const input = modalities(architecture?.input_modalities);
  const output = modalities(architecture?.output_modalities);
  if (!output.includes("image")) return undefined;
  if (input.length === 0) input.push("text");
  const inputPrice = price(sourcePricing?.prompt);
  const outputPrice = price(sourcePricing?.completion);
  const cacheReadPrice = price(sourcePricing?.input_cache_read);
  const cacheWritePrice = price(sourcePricing?.input_cache_write);
  const pricing = inputPrice !== undefined && outputPrice !== undefined
    && cacheReadPrice !== undefined && cacheWritePrice !== undefined
    ? { input: inputPrice, output: outputPrice, cacheRead: cacheReadPrice, cacheWrite: cacheWritePrice }
    : undefined;
  const model: GeneratedModel = { id: value.id, name: value.name, input, output };
  if (pricing !== undefined) model.pricing = pricing;
  return model;
}

async function catalog(): Promise<GeneratedModel[]> {
  const response = await fetch(`${BASE_URL}/models?output_modalities=image`, { redirect: "error" });
  if (!response.ok) throw new Error(`Image catalog request failed with HTTP ${response.status}`);
  const declared = Number(response.headers.get("content-length"));
  if (Number.isFinite(declared) && declared > MAX_CATALOG_BYTES) throw new Error("Image catalog response is too large");
  const text = await response.text();
  if (Buffer.byteLength(text, "utf8") > MAX_CATALOG_BYTES) throw new Error("Image catalog response is too large");
  const parsed: JsonValue = JSON.parse(text);
  const data = isJsonObject(parsed) ? parsed.data : undefined;
  if (!Array.isArray(data)) throw new Error("Image catalog response did not contain a model array");
  const models = data.slice(0, 512).map(parseModel).filter((entry): entry is GeneratedModel => entry !== undefined);
  if (models.length === 0) throw new Error("Image catalog did not contain any usable image models");
  return models.sort((left, right) => left.id.localeCompare(right.id));
}

function source(models: readonly GeneratedModel[]): string {
  const entries = models.map((entry) => `  {
    id: ${JSON.stringify(entry.id)},
    name: ${JSON.stringify(entry.name)},
    api: "openrouter-images",
    provider: "openrouter",
    baseUrl: ${JSON.stringify(BASE_URL)},
    input: ${JSON.stringify(entry.input)},
    output: ${JSON.stringify(entry.output)},${entry.pricing === undefined ? "" : `
    pricing: ${JSON.stringify(entry.pricing)},`}
  },`).join("\n");
  return `// Generated by scripts/generate-image-models.ts. Do not edit by hand.
import type { ImagesModel } from "./types.js";

export const OPENROUTER_IMAGE_MODELS = [
${entries}
] as const satisfies readonly ImagesModel<"openrouter-images">[];
`;
}

const models = await catalog();
await writeFile(OUTPUT, source(models), "utf8");
process.stdout.write(`Generated ${models.length} image models at ${OUTPUT}\n`);
