export { detectTerminalCapabilities, detectTerminalProtocols, terminalSize } from "./capabilities.js";
export {
  DEFAULT_RUNTIME_UI_MAX_BYTES,
  DEFAULT_RUNTIME_UI_MAX_LINES,
  DEFAULT_RUNTIME_UI_MAX_SPANS_PER_LINE,
  RuntimeUiComponentMount,
  runtimeUiKeyEvent,
  sanitizeRuntimeUiBlock,
  sanitizeRuntimeUiRenderContext,
  type RuntimeUiBlock,
  type RuntimeUiBlockLimits,
  type RuntimeUiComponent,
  type RuntimeUiComponentFactory,
  type RuntimeUiComponentHandle,
  type RuntimeUiComponentHost,
  type RuntimeUiComponentMountOptions,
  type RuntimeUiCustomOptions,
  type RuntimeUiKeyEvent,
  type RuntimeUiLine,
  type RuntimeUiOverlayAnchor,
  type RuntimeUiOverlayHandle,
  type RuntimeUiOverlayLength,
  type RuntimeUiOverlayMargin,
  type RuntimeUiOverlayOptions,
  type RuntimeUiOverlayUnfocusOptions,
  type RuntimeUiPointerEvent,
  type RuntimeUiPointerResponse,
  type RuntimeUiRenderContext,
  type RuntimeUiRenderResult,
  type RuntimeUiSpan,
  type RuntimeEditorRenderer,
  type RuntimeEditorRendererBinding,
  type RuntimeEditorRenderView,
  type RuntimeToolRenderer,
  type RuntimeToolRendererBinding,
  type RuntimeToolRendererFailure,
  type RuntimeToolRenderContentBlock,
  type RuntimeToolRenderImageDescriptor,
  type RuntimeToolRenderProgress,
  type RuntimeToolRenderResult,
  type RuntimeToolRenderUsage,
  type RuntimeToolRenderView,
  type RuntimeSessionRendererBinding,
} from "./components.js";
export {
  uiMarkdown,
  uiPanel,
  uiStack,
  uiText,
  type RuntimeUiMarkdownOptions,
  type RuntimeUiPanelOptions,
  type RuntimeUiStackOptions,
  type RuntimeUiTextOptions,
  type RuntimeUiView,
} from "./component-kit.js";
export { TuiSelectionCancelledError, DEFAULT_TUI_LIMITS } from "./controller.js";
export { TuiController } from "./public-controller.js";
export { createInteractiveDirectUiContext } from "./direct-ui.js";
export { projectPortablePresentationToRuntimeUiBlock } from "./portable-presentation.js";
export type {
  FooterActivitySnapshot,
  FooterDataSnapshot,
  FooterWorkingIndicatorSnapshot,
  ReadonlyFooterDataProvider,
} from "./footer-data.js";
export {
  MultilineEditor,
  type EditorOptions as MultilineEditorOptions,
  type EditorPasteSnapshot,
  type EditorSnapshot,
  type TuiEditorImplementation,
} from "./editor.js";
export { editTextExternally, parseEditorCommand } from "./external-editor.js";
export { fuzzyScore, rankPickerItems } from "./fuzzy.js";
export { fuzzyFilter, fuzzyMatch, type FuzzyMatch } from "@ohm/terminal";
export { KeyDecoder, type KeyEvent, type TerminalReply } from "./keys.js";
export {
  DEFAULT_KEYBINDINGS,
  KEYBINDING_ACTIONS,
  Keybindings as ConfiguredKeybindings,
  keybindingForEvent,
  loadKeybindings,
  normalizeKeybinding,
  parseKeybindings,
  type AppKeybindings,
  type KeybindingAction,
  type KeybindingOverrides,
} from "./keybindings.js";
export {
  getKeybindings,
  KeybindingsManager,
  setKeybindings,
  TUI_KEYBINDINGS,
  type Keybinding,
  type KeybindingConflict,
  type KeybindingDefinition,
  type KeybindingDefinitions,
  type KeybindingsConfig,
  type Keybindings,
} from "@ohm/terminal";
export {
  decodeKittyPrintable,
  decodePrintableKey,
  isKeyRelease,
  isKeyRepeat,
  isKittyProtocolActive,
  Key,
  matchesKey,
  parseKey,
  setKittyProtocolActive,
  type KeyEventType,
  type KeyId,
} from "@ohm/terminal";
export { renderTranscript, renderTranscriptFrame, pickerItem, type TranscriptRenderOptions } from "./layout.js";
export {
  buildSessionPickerRows,
  formatSessionAge,
  type SessionPickerOptions,
  type SessionPickerRow,
  type SessionPickerSortMode,
  type SessionPickerTimestamp,
} from "./session-picker.js";
export {
  buildSessionTreePickerRows,
  SESSION_TREE_FILTER_MODES,
  sessionTreeEndpointIndex,
  type SessionTreeFilterMode,
  type SessionTreePickerOptions,
} from "./session-tree-picker.js";
export { TuiModel } from "./model.js";
export {
  createNativeUiHost,
  createUnsafeTerminalHost,
  type NativeUiAutocompleteWrapper,
  type NativeUiControllerBridge,
  type NativeUiDisposer,
  type NativeUiEditorWrapper,
  type NativeUiHost,
  type NativeUiInputHandler,
  type NativeUiInputResult,
  type UnsafeTerminalHost,
  type UnsafeTerminalInputHandler,
  type UnsafeTerminalInputResult,
} from "./native-ui.js";
export {
  CombinedAutocompleteProvider,
  type AutocompleteItem,
  type AutocompleteProvider,
  type AutocompleteSuggestions,
  type SlashCommand,
} from "@ohm/terminal";
export {
  Box,
  CancellableLoader,
  Editor,
  FullscreenTUI,
  HStack,
  Image,
  Input,
  Loader,
  Marked,
  Markdown,
  ScrollView,
  SelectList,
  SettingsList,
  Spacer,
  Text,
  TuiAltScreen,
  TuiMainScreen,
  TruncatedText,
  VStack,
  type DefaultTextStyle,
  type EditorComponent,
  type EditorOptions,
  type EditorTheme,
  type FullscreenTUIOptions,
  type ImageOptions,
  type ImageTheme,
  type LoaderIndicatorOptions,
  type MarkdownOptions,
  type MarkdownTheme,
  type RenderLatexOptions,
  type ScrollbarVisibility,
  type ScrollViewOptions,
  type ScrollViewScrollbar,
  type ScrollViewScrollToOptions,
  type SelectItem,
  type SelectListLayoutOptions,
  type SelectListTheme,
  type SelectListTruncatePrimaryContext,
  type SettingItem,
  type SettingsListOptions,
  type SettingsListTheme,
  type StackChild,
  type StackEntry,
  type StackEntryOptions,
  type StackOptions,
  type TuiAltScreenOptions,
  type Token,
  type Tokens,
} from "@ohm/terminal";
export { renderLatex } from "@ohm/terminal";
export {
  type BackgroundCell,
  type BackgroundComponent,
  Container,
  CURSOR_MARKER,
  isFocusable,
  TUI,
  type Component,
  type Focusable,
  type OverlayAnchor,
  type OverlayHandle,
  type OverlayMargin,
  type OverlayOptions,
  type OverlayUnfocusOptions,
  type SizeValue,
  type TuiInputListener,
  type TuiInputListenerResult,
  type TuiMainScreenRenderState,
  type TuiStopOptions,
  type ViewportTUI,
} from "@ohm/terminal";
export {
  compositeTerminalLine,
  compositeTuiLine,
  compositeTerminalRows,
  cancelViewportPointer,
  dispatchViewportPointer,
  fitViewportRows,
  isViewportPointerTarget,
  isViewportTUI,
  isViewportComponent,
  renderViewport,
  VIEWPORT_COMPONENT,
  VIEWPORT_POINTER_REGIONS,
  VIEWPORT_POINTER_TARGET,
  type TerminalRowsCompositeOptions,
  type ViewportComponent,
  type ViewportPointerDispatchResult,
  type ViewportPointerEvent,
  type ViewportPointerRegion,
  type ViewportPointerRegionComponent,
  type ViewportPointerResponse,
  type ViewportPointerTarget,
  type ViewportSize,
} from "@ohm/terminal";
export { ProcessTerminal, type ProcessTerminalOptions, type Terminal } from "@ohm/terminal";
export { StdinBuffer, type StdinBufferEventMap, type StdinBufferOptions } from "@ohm/terminal";
export {
  detectCapabilities,
  getCapabilities,
  getCellDimensions,
  resetCapabilitiesCache,
  setCapabilities,
  setCapabilityOverrides,
  setCellDimensions,
  type CellDimensions,
  type TerminalCapabilities,
} from "@ohm/terminal";
export {
  calculateImageCellSize,
  calculateImageRows,
  getGifDimensions,
  getImageDimensions,
  getJpegDimensions,
  getPngDimensions,
  getWebpDimensions,
  type ImageCellSize,
  type ImageDimensions,
} from "@ohm/terminal";
export {
  allocateImageId,
  deleteAllKittyImages,
  encodeITerm2,
  encodeKitty,
  hyperlink,
  imageFallback,
  isImageLine,
  renderImage,
  type ImageProtocol,
  type ImageRenderOptions,
} from "@ohm/terminal";
export {
  DEFAULT_TERMINAL_CELL_DIMENSIONS,
  ITERM_IMAGE_CHUNK_BYTES,
  KITTY_IMAGE_CHUNK_BYTES,
  MAX_TERMINAL_IMAGE_AGGREGATE_BYTES,
  MAX_TERMINAL_IMAGE_CHUNKS,
  MAX_TERMINAL_IMAGE_COUNT,
  TerminalImageRegistry,
  allocateTerminalImageId,
  calculateTerminalImageCells,
  composeTerminalImageOutput,
  deleteKittyImage,
  encodeITerm2Image,
  encodeKittyImage,
  encodeTerminalImage,
  terminalImageFallback,
  trustedHyperlinkTarget,
  trustedTerminalHyperlink,
  validateTerminalImage,
  validateTerminalImagePlacement,
  type TerminalCellDimensions,
  type TerminalImagePlacement,
  type TerminalImageProtocol,
  type TerminalImageResolution,
  type TranscriptImage,
  type ValidatedTerminalImage,
} from "./terminal-image.js";
export {
  createTheme,
  parseAutomaticThemePair,
  parseThemeDefinition,
  resolveThemeSetting,
  style,
  themeContrastDiagnostics,
  THEME_ROLES,
  THEME_SCHEMA_URI,
  THEME_TOKENS,
  type Theme,
  type AutomaticThemePair,
  type ThemeColorValue,
  type ThemeContrastDiagnostic,
  type ThemeDefinition,
  type ThemeExportDefinition,
  type ThemeRole,
  type ThemeStyleDefinition,
  type ThemeToken,
} from "./theme.js";
export {
  parseTerminalBackgroundReply,
  parseTerminalColorSchemeReply,
  terminalColorSchemeForRgb,
  terminalColorSchemeFromEnvironment,
  type TerminalColorScheme,
  type TerminalRgbColor,
} from "./terminal-colors.js";
export {
  isOsc11BackgroundColorResponse,
  parseOsc11BackgroundColor,
  parseTerminalColorSchemeReport,
  type RgbColor,
} from "@ohm/terminal";
export { fileReferenceQuery, scanWorkspaceFiles, type WorkspaceFileScanOptions } from "./workspace-files.js";
export {
  byteTruncate,
  cellWidth,
  graphemeWidth,
  padCells,
  sanitizeTerminalText,
  splitGraphemes,
  stripAnsi,
  truncateCells,
  wrapCells,
} from "./unicode.js";
export {
  getOsc8LinkAtColumn,
  sliceByColumn,
  stripTerminalSequences,
  truncateToWidth,
  visibleWidth,
  wrapTextWithAnsi,
} from "@ohm/terminal";
export type {
  EventRenderer,
  BuiltinThemeName,
  Frame,
  PickerCatalog,
  PickerItem,
  PickerKind,
  QueuedMessage,
  SessionPickerMetadata,
  SessionTreeMetadata,
  TerminalCapabilities as ControllerTerminalCapabilities,
  TerminalChoice,
  ThemeName,
  TranscriptEntry,
  TuiAction,
  TuiAutocompleteCompletion,
  TuiAutocompleteProvider,
  TuiCommandArgumentCompletion,
  TuiCommandCompletionProvider,
  TuiContext,
  TuiControllerOptions,
  TuiEditorMiddleware,
  TuiEditorMiddlewareEvent,
  TuiEditorMiddlewareResult,
  TuiEditorMiddlewareSnapshot,
  TuiExtensionShortcut,
  TuiInput,
  TuiInputImageAttachment,
  TuiInputImageSummary,
  TuiLimits,
  TuiMode,
  TuiNormalizedKeyObserver,
  TuiOperatorPreferences,
  TuiOutput,
  TuiPersistentComponentSlot,
  TuiSignalSource,
  TuiSettingItem,
  TuiThemeChange,
  TuiViewState,
  TuiWorkingIndicatorOptions,
} from "./types.js";
export {
  currentTheme,
  getEditorTheme,
  getLanguageFromPath,
  getMarkdownTheme,
  getSelectListTheme,
  getSettingsListTheme,
  highlightCode,
  initTheme,
  keyHint,
  keyText,
  rawKeyHint,
  type ThemeColor,
} from "./public-theme.js";
export * from "./public-components.js";
