// Generated by scripts/generate-provider-models.mjs from ohm's maintained catalog. Do not edit.
import type { ProviderModel } from "./models.js";

function model(value: ProviderModel): ProviderModel {
  return value;
}

const MODELS: ProviderModel[] = [
  model({
    "id": "gpt-5.6",
    "name": "gpt-5.6",
    "api": "openai-responses",
    "provider": "openai",
    "baseUrl": "https://api.openai.com/v1",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": "max"
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 5,
      "output": 30,
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "tiers": [
        {
          "inputTokensAbove": 272000,
          "input": 10,
          "output": 45,
          "cacheRead": 1,
          "cacheWrite": 12.5
        }
      ]
    },
    "contextWindow": 1050000,
    "maxInputTokens": 922000,
    "maxTokens": 128000,
    "compat": {
      "supportsExplicitPromptCacheMode": true,
      "supportsPromptCacheBreakpoints": true
    }
  }),
  model({
    "id": "gpt-5.6-sol",
    "name": "gpt-5.6-sol",
    "api": "openai-responses",
    "provider": "openai",
    "baseUrl": "https://api.openai.com/v1",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": "max"
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 5,
      "output": 30,
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "tiers": [
        {
          "inputTokensAbove": 272000,
          "input": 10,
          "output": 45,
          "cacheRead": 1,
          "cacheWrite": 12.5
        }
      ]
    },
    "contextWindow": 1050000,
    "maxInputTokens": 922000,
    "maxTokens": 128000,
    "compat": {
      "supportsExplicitPromptCacheMode": true,
      "supportsPromptCacheBreakpoints": true
    }
  }),
  model({
    "id": "gpt-5.6-terra",
    "name": "gpt-5.6-terra",
    "api": "openai-responses",
    "provider": "openai",
    "baseUrl": "https://api.openai.com/v1",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": "max"
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 2,
      "output": 12,
      "cacheRead": 0.2,
      "cacheWrite": 2.5,
      "tiers": [
        {
          "inputTokensAbove": 272000,
          "input": 4,
          "output": 18,
          "cacheRead": 0.4,
          "cacheWrite": 5
        }
      ]
    },
    "contextWindow": 1050000,
    "maxInputTokens": 922000,
    "maxTokens": 128000,
    "compat": {
      "supportsExplicitPromptCacheMode": true,
      "supportsPromptCacheBreakpoints": true
    }
  }),
  model({
    "id": "gpt-5.6-luna",
    "name": "gpt-5.6-luna",
    "api": "openai-responses",
    "provider": "openai",
    "baseUrl": "https://api.openai.com/v1",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": "max"
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.2,
      "output": 1.2,
      "cacheRead": 0.02,
      "cacheWrite": 0.25,
      "tiers": [
        {
          "inputTokensAbove": 272000,
          "input": 0.4,
          "output": 1.8,
          "cacheRead": 0.04,
          "cacheWrite": 0.5
        }
      ]
    },
    "contextWindow": 1050000,
    "maxInputTokens": 922000,
    "maxTokens": 128000,
    "compat": {
      "supportsExplicitPromptCacheMode": true,
      "supportsPromptCacheBreakpoints": true
    }
  }),
  model({
    "id": "gpt-5.4",
    "name": "gpt-5.4",
    "api": "openai-responses",
    "provider": "openai",
    "baseUrl": "https://api.openai.com/v1",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": null
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 2.5,
      "output": 15,
      "cacheRead": 0.25,
      "cacheWrite": 0,
      "tiers": [
        {
          "inputTokensAbove": 272000,
          "input": 5,
          "output": 22.5,
          "cacheRead": 0.5,
          "cacheWrite": 0
        }
      ]
    },
    "contextWindow": 1050000,
    "maxInputTokens": 922000,
    "maxTokens": 128000
  }),
  model({
    "id": "gpt-5.4-mini",
    "name": "gpt-5.4-mini",
    "api": "openai-responses",
    "provider": "openai",
    "baseUrl": "https://api.openai.com/v1",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": null
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.75,
      "output": 4.5,
      "cacheRead": 0.075,
      "cacheWrite": 0
    },
    "contextWindow": 400000,
    "maxInputTokens": 272000,
    "maxTokens": 128000
  }),
  model({
    "id": "gpt-5.4-nano",
    "name": "gpt-5.4-nano",
    "api": "openai-responses",
    "provider": "openai",
    "baseUrl": "https://api.openai.com/v1",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": null
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.2,
      "output": 1.25,
      "cacheRead": 0.02,
      "cacheWrite": 0
    },
    "contextWindow": 400000,
    "maxInputTokens": 272000,
    "maxTokens": 128000
  }),
  model({
    "id": "claude-fable-5",
    "name": "claude-fable-5",
    "api": "anthropic-messages",
    "provider": "anthropic",
    "baseUrl": "https://api.anthropic.com",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": null,
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": "max"
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 10,
      "output": 50,
      "cacheRead": 1,
      "cacheWrite": 12.5
    },
    "contextWindow": 1000000,
    "maxTokens": 128000
  }),
  model({
    "id": "claude-opus-5",
    "name": "claude-opus-5",
    "api": "anthropic-messages",
    "provider": "anthropic",
    "baseUrl": "https://api.anthropic.com",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "disabled",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": "max"
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite": 6.25
    },
    "contextWindow": 1000000,
    "maxTokens": 128000
  }),
  model({
    "id": "claude-opus-4-8",
    "name": "claude-opus-4-8",
    "api": "anthropic-messages",
    "provider": "anthropic",
    "baseUrl": "https://api.anthropic.com",
    "reasoning": true,
    "thinkingLevelMap": {
      "off": "off",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": "max"
    },
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite": 6.25
    },
    "contextWindow": 1000000,
    "maxTokens": 128000
  }),
  model({
    "id": "claude-haiku-4-5",
    "name": "claude-haiku-4-5",
    "api": "anthropic-messages",
    "provider": "anthropic",
    "baseUrl": "https://api.anthropic.com",
    "reasoning": false,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 1,
      "output": 5,
      "cacheRead": 0.1,
      "cacheWrite": 1.25
    },
    "contextWindow": 200000,
    "maxTokens": 64000
  }),
  model({
    "id": "claude-haiku-4-5-20251001",
    "name": "claude-haiku-4-5-20251001",
    "api": "anthropic-messages",
    "provider": "anthropic",
    "baseUrl": "https://api.anthropic.com",
    "reasoning": false,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 1,
      "output": 5,
      "cacheRead": 0.1,
      "cacheWrite": 1.25
    },
    "contextWindow": 200000,
    "maxTokens": 64000
  }),
];

export const BUILTIN_MODEL_CATALOG: readonly ProviderModel[] = Object.freeze(MODELS);
