/**
 * Public type-only assembly point for the provider-neutral models contract.
 * Capability declarations live in focused modules so their dependencies and
 * ownership remain reviewable without adding runtime exports.
 */
export type {
  AgentMessage,
  AssistantContent,
  AssistantMessage,
  AssistantMessageDiagnostic,
  AssistantMessageDiagnosticError,
  Context,
  CustomMessage,
  ImageContent,
  Message,
  ProviderState,
  ProviderStateSource,
  StopReason,
  TextContent,
  ThinkingContent,
  ToolCall,
  ToolResultMessage,
  UserMessage,
} from "./contracts/content-messages.js";

export type { JsonObject, JsonValue } from "./contracts/json-values.js";

export type {
  Api,
  ApiStreamOptions,
  AssistantMessageEvent,
  AssistantMessageEventStream,
  CacheRetention,
  ConstrainedSampling,
  ConstrainedSamplingConfig,
  GrammarConstraint,
  GrammarFormat,
  GrammarSamplingConfig,
  GrammarSyntax,
  JsonSchemaConstraint,
  KnownApi,
  Model,
  ModelChatTemplateValue,
  ModelChatTemplateVariable,
  ModelCompatibility,
  ModelCost,
  ModelCostTier,
  ModelId,
  ModelOpenRouterRouting,
  ModelReasoningEffort,
  ModelVercelGatewayRouting,
  ModelsApiStreamOptions,
  ModelsSimpleStreamOptions,
  ProviderHeaders,
  ProviderId,
  PushableAssistantMessageEventStream,
  RequestDiagnostic,
  ResponseDiagnostic,
  SimpleStreamOptions,
  StreamFn,
  StreamOptions,
  ThinkingBudgets,
  ThinkingLevel,
  Tool,
  ToolChoice,
  Transport,
  Usage,
  UsageCost,
} from "./contracts/models-sampling-streaming.js";

export type {
  ApiKeyAuth,
  ApiKeyCredential,
  AuthCheck,
  AuthContext,
  AuthInteraction,
  AuthMethod,
  AuthNotification,
  AuthPrompt,
  AuthResult,
  AuthType,
  Credential,
  CredentialInfo,
  CredentialStore,
  Models,
  ModelsRefreshOptions,
  ModelsRefreshResult,
  ModelsStreamTransforms,
  MutableModels,
  OAuthAuth,
  OAuthCredential,
  OAuthCredentials,
  OAuthLoginCallbacks,
  Provider,
  ProviderAccountAuth,
  ProviderApiKeyCredential,
  ProviderAuth,
  ProviderAuthCheck,
  ProviderCatalogCacheEntry,
  ProviderCatalogStore,
  RefreshModelsContext,
  ResolvedAuth,
} from "./contracts/credentials-auth-providers-catalog.js";

export type {
  GeneratedImage,
  ImageModel,
  ImageProvider,
  ImageRequest,
  ImageResult,
  RetryCallbacks,
  RetryPolicy,
} from "./contracts/images-retry.js";
